### ISSUE TITLE
Query fails if it contains Group_Concat expression with a custom separator

### ISSUE THREAD

**Issue by renarl** [Complexible/stardog.js#39] opened 2014-12-15 11:42 UTC
I can't get results for queries that contain a Group_Concat with a custom separator. It seems that the ';', which is required before a custom separator, is being interpreted as EOF.

For example, the following query works fine:
 ```javascript
'select ?s (Group_Concat(?o) as ?o_s) where { ?s <#name> ?o } group by ?s'
```
But if I add a custom seperator, e.g.
 ```javascript
'select ?s (Group_Concat(?o ; separator=",") as ?o_s) where { ?s <#name> ?o } group by ?s'
```
it fails with the following:
 ```javascript
'POST http://localhost:5820/testDB/query?reasoning=NONE 400 (Encountered "<EOF>" at line 1, column 29. Was expecting one of:     ")" ...     ";" ...     "=" ...     "!=" ...     ">" ...     "<" ...     "<=" ...     ">=" ...     "||" ...     "&&" ...     "+" ...     "-" ...     "*" ...     "/" ...     "in" ...     "not in" ...     <INTEGER_POSITIVE> ...     <INTEGER_NEGATIVE> ...     <DECIMAL_POSITIVE> ...     <DECIMAL_NEGATIVE> ...     <DOUBLE_POSITIVE> ...     <DOUBLE_NEGATIVE> ...)'
```

**Comment by edgarRd** [comment] 2015-02-17 15:42
Which version of stardog are you using? Is this happening only when the query is issued via `stardog.js` or does it happen when executing the query in the stardog CLI with the `stardog query` command?

**Comment by edgarRd** [comment] 2015-02-18 15:44
I was not able to reproduce the issue with the test case committed in https://github.com/clarkparsia/stardog.js/commit/9b8781c728f1bc5f717618593f3af410e8c1119a using the latest stardog.js `1.6` and stardog `2.2.4`.

You could try running the test case having stardog running, with the following commands in the repo directory:
1. Install node modules: `npm install`
2. Load test data: `./load_test_data.sh`
3. Run the test case: `node_modules/mocha/bin/mocha -R spec test/query.group_concat.spec.js`

**Closed** 2015-06-10 18:51 UTC
Labels: wontfix
